feat: Chapter 6 Shell Grammar
ShadowRZ/zshdocs-zh pull request #1
Opened 2021-01-27 10:38 UTC by CoelacanthusHex

- [x] 6.1 Simple Commands & Pipelines
- [ ] 6.2 Precommand Modifiers
- [ ] 6.3 Complex Commands
- [ ] 6.4 Alternate Forms For Complex Commands
- [ ] 6.5 Reserved Words
- [ ] 6.6 Errors
- [ ] 6.7 Comments
- [ ] 6.8 Aliasing
- [ ] 6.9 Quoting

Co-authored-by: MingqiHuang <Mingqi.Huang@yandex.com>

2021-02-01 13:31 UTC, ShadowRZ requested changes
这样应该差不多了，一些缩进问题待我可以合并后会自行解决（你就不用处理了）

2021-02-01 13:31 UTC, ShadowRZ commented on content/06-shell-grammer.md
> +否，因为测试没有适当划分界限。
应该改成（Suggest 结果坏了所以没用）：
:   if的替代形式。上述规则意味着
```zsh
if [[ -o ignorebraces ]] {
  print yes
}
```
可以工作，但是
```zsh
if true {  # 不起作用！
  print yes
}
```
_并不会_ ，因为测试没有适当划分界限。

2021-02-01 13:31 UTC, ShadowRZ commented on content/06-shell-grammer.md
> +:   替代 `if` 的简短形式。列表形式的限制与以前的形式相同。
```suggestion
:   替代 `if` 的简短形式。列表形式的限制与上一个形式相同。
```

2021-02-01 13:31 UTC, ShadowRZ commented on content/06-shell-grammer.md
> +如果将选项 `SH_GLOB` 设置为与其他 shell 兼容，则当一个单词时，左右括号之间可能会出现空格；否则，在这种情况下，括号将被视为形成球形图案。
括号将被视为形成球形图案？

2021-02-01 13:56 UTC, CoelacanthusHex commented
我最近精神状态不是很好，后续翻译也不好参与，就 Ready for review 了

2021-10-02 23:08 UTC, ShadowRZ approved these changes

2021-10-02 23:09 UTC, merged